# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 16:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    replaces = [('auctionapp', '0001_initial')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assetType', models.CharField(max_length=16)),
                ('sourceSite', models.CharField(max_length=36)),
            ],
        ),
        migrations.AddField(
            model_name='auction',
            name='type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auctionapp.Type'),
        ),
    ]
