# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 16:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import datetime


class Migration(migrations.Migration):
    dependencies = [
        ('auctionapp', '0001_squashed_0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='type',
        ),
        migrations.AddField(
            model_name='auction',
            name='asset_type',
            field=models.CharField(default='', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auction',
            name='auctioneer_name',
            field=models.CharField(default='', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auction',
            name='auctioneer_vat_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auction',
            name='date_imported',
            field=models.DateField(default=datetime.datetime.now()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auction',
            name='debtor_name',
            field=models.CharField(default='', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auction',
            name='debtor_vat_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auction',
            name='offer_price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auction',
            name='published_date',
            field=models.DateField(default=datetime.datetime.now()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auction',
            name='source',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='auctionapp.Type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auction',
            name='unique_code',
            field=models.CharField(default='', max_length=16),
            preserve_default=False,
        ),
    ]
