# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-06 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctionapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('description1', models.CharField(blank=True, max_length=150, null=True)),
                ('type', models.CharField(blank=True, max_length=150, null=True)),
                ('place', models.CharField(blank=True, max_length=250, null=True)),
                ('area', models.CharField(blank=True, max_length=250, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'poi',
                'managed': False,
            },
        ),
    ]
