# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-15 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctionapp', '0002_poi'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoCities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'geo_cities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PropAuction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('percentage', models.CharField(blank=True, max_length=150, null=True)),
                ('img_url', models.CharField(blank=True, max_length=250, null=True)),
                ('unique_id', models.CharField(blank=True, max_length=250, null=True)),
                ('performance_category', models.CharField(blank=True, max_length=250, null=True)),
                ('suggest_price', models.FloatField(blank=True, null=True)),
                ('suggest_income', models.FloatField(blank=True, null=True)),
                ('category_major', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('updated_date', models.DateField(blank=True, null=True)),
                ('profit_loss_income', models.FloatField(blank=True, null=True)),
                ('embadon', models.FloatField(blank=True, null=True)),
                ('other', models.TextField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('asset_type', models.CharField(blank=True, max_length=150, null=True)),
                ('address', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'prop_auction',
                'managed': False,
            },
        ),
    ]
