# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('auctionapp', '0002_auto_20161120_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='asset_type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='auction',
            name='auctioneer_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='auction',
            name='debtor_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='auction',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='auction',
            name='unique_code',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='type',
            name='assetType',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='type',
            name='sourceSite',
            field=models.URLField(max_length=255),
        ),
    ]
