# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 19:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('auctionapp', '0003_auto_20161120_1836'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_site', models.URLField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='type',
            name='assetType',
        ),
        migrations.RemoveField(
            model_name='type',
            name='sourceSite',
        ),
        migrations.AddField(
            model_name='type',
            name='asset_type',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auction',
            name='asset_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctionapp.Type'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctionapp.Source'),
        ),
    ]
