# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-07 13:47
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctionapp', '0003_geocities_propauction'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('category_major', models.CharField(blank=True, max_length=150, null=True)),
                ('synonyms', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'asset_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GeoAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'geo_address',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PoiType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_major', models.CharField(blank=True, max_length=150, null=True)),
                ('category_minor', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), blank=True, null=True, size=None)),
            ],
            options={
                'db_table': 'poi_type',
                'managed': False,
            },
        ),
    ]
