# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('auctionapp', '0004_auto_20161120_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='auction_url',
            field=models.URLField(blank=True, max_length=250, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='asset_type',
            field=models.IntegerField(choices=[(1, 'Real estate'), (2, 'Cars')]),
        ),
        migrations.AlterField(
            model_name='auction',
            name='date_imported',
            field=models.DateField(auto_created=True),
        ),
    ]
