# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 09:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('auctionapp', '0005_auto_20161122_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='asset_address',
            field=models.CharField(default='', editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name='auction',
            name='asset_city',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='auction',
            name='asset_zip',
            field=models.CharField(default='', editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name='auction',
            name='auction_date',
            field=models.DateField(default=datetime.datetime(2010, 1, 1, 1, 10)),
        ),
        migrations.AddField(
            model_name='auction',
            name='auction_num',
            field=models.IntegerField(default=1, editable=False),
        ),
        migrations.AlterField(
            model_name='auction',
            name='auctioneer_vat_number',
            field=models.CharField(default='', editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='auction',
            name='date_imported',
            field=models.DateField(default=datetime.datetime(2016, 11, 24, 9, 59, 21, 513642, tzinfo=utc),
                                   editable=False),
        ),
        migrations.AlterField(
            model_name='auction',
            name='debtor_name',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AlterField(
            model_name='auction',
            name='debtor_vat_number',
            field=models.CharField(default='', editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='auction',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='auction',
            name='offer_price',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='auction',
            name='published_date',
            field=models.DateField(default=datetime.datetime(2010, 1, 1, 1, 10)),
        ),
        migrations.AlterUniqueTogether(
            name='auction',
            unique_together=set([('name', 'asset_type')]),
        ),
    ]
