# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 10:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('auctionapp', '0006_auto_20161124_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='date_imported',
            field=models.DateField(default=datetime.datetime(2016, 11, 24, 10, 1, 38, 43742, tzinfo=utc),
                                   editable=False),
        ),
        migrations.AlterField(
            model_name='auction',
            name='unique_code',
            field=models.CharField(default='', editable=False, max_length=255),
        ),
    ]
