# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 10:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('auctionapp', '0007_auto_20161124_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='source_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='source',
            name='source_type',
            field=models.IntegerField(choices=[(1, 'Bank'), (2, 'Leasing')], default=1),
        ),
        migrations.AlterField(
            model_name='auction',
            name='date_imported',
            field=models.DateField(default=datetime.datetime(2016, 11, 24, 10, 6, 43, 938200, tzinfo=utc),
                                   editable=False),
        ),
    ]
