BEGIN;
SELECT setval(pg_get_serial_sequence('"auctionapp_auction"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "auctionapp_auction";
SELECT setval(pg_get_serial_sequence('"asset"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "asset";
SELECT setval(pg_get_serial_sequence('"asset_car"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "asset_car";
SELECT setval(pg_get_serial_sequence('"asset_property"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "asset_property";
SELECT setval(pg_get_serial_sequence('"asset_type"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "asset_type";
SELECT setval(pg_get_serial_sequence('"cooperator"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "cooperator";
SELECT setval(pg_get_serial_sequence('"django_migrations"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "django_migrations";
SELECT setval(pg_get_serial_sequence('"geo_areas"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "geo_areas";
SELECT setval(pg_get_serial_sequence('"geo_cities"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "geo_cities";
SELECT setval(pg_get_serial_sequence('"geo_countries"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "geo_countries";
SELECT setval(pg_get_serial_sequence('"geo_regions"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "geo_regions";
SELECT setval(pg_get_serial_sequence('"geo_address"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "geo_address";
SELECT setval(pg_get_serial_sequence('"prop_commercial"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "prop_commercial";
SELECT setval(pg_get_serial_sequence('"prop_earth"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "prop_earth";
SELECT setval(pg_get_serial_sequence('"prop_residential"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "prop_residential";
SELECT setval(pg_get_serial_sequence('"prop_auction"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "prop_auction";
SELECT setval(pg_get_serial_sequence('"search_info"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "search_info";
SELECT setval(pg_get_serial_sequence('"sources"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "sources";
SELECT setval(pg_get_serial_sequence('"tran_auction"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "tran_auction";
SELECT setval(pg_get_serial_sequence('"tran_commercial"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "tran_commercial";
SELECT setval(pg_get_serial_sequence('"transaction"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "transaction";
SELECT setval(pg_get_serial_sequence('"poi"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "poi";
SELECT setval(pg_get_serial_sequence('"poi_type"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "poi_type";
COMMIT;
